# Synthetic filesystem fixture only. No birth records are read or models fitted.
source("model-fitting/run_current.R")
plan<-current_analysis_plan()
stopifnot(nrow(plan)==53L,all(file.exists(file.path("model-fitting/current",plan$script))),
  !any(grepl("imput|bias_scenarios|supplementary_bias",plan$script)))
before<-list.files("output",recursive=TRUE,all.files=TRUE)
source("run_all.R")
stopifnot(identical(before,list.files("output",recursive=TRUE,all.files=TRUE)))
fixture<-tempfile("smoking_runner_inputs_");dir.create(fixture)
must_fail<-function(expr){failed<-inherits(try(force(expr),silent=TRUE),"try-error");stopifnot(failed)}
must_fail(current_preflight(fixture,check_packages=FALSE))
put<-function(relative){p<-file.path(fixture,"age45_revision/derived",relative);dir.create(dirname(p),recursive=TRUE,showWarnings=FALSE);writeLines("synthetic preflight fixture, not a record file",p)}
for(ct in c("primary","broad","prepregnancy"))for(y in if(ct=="primary")2014:2024 else 2016:2024)
  for(ext in c(".rds","_receipt.json"))put(file.path("model_inputs",paste0(y,"_",ct,ext)))
for(ct in c("within_ext","prepregnancy_ext"))for(y in 2016:2024)for(ext in c(".rds","_receipt.json"))put(file.path("supplementary_inputs",paste0(y,"_",ct,ext)))
for(y in 2016:2024)put(file.path("natality",paste0(y,"_ledger.csv")))
for(prefix in c("gh","fetal_endpoint"))for(tier in c("shared_core","shared_augmented"))
  for(src in c("natality","fetal_death"))for(y in 2018:2024)for(ext in c(".rds","_receipt.json"))
    put(file.path("adjunct_models",paste0(paste(prefix,y,src,tier,sep="_"),ext)))
for(ep in c("infant","neonatal","early_neonatal"))for(ext in c(".rds","_receipt.json"))
  put(file.path("adjunct_models",paste0("linked_",ep,ext)))
stopifnot(current_preflight(fixture,check_packages=FALSE)$required_files==221L)
hold<-file.path(fixture,"age45_revision/derived/adjunct_models/linked_infant_receipt.json")
stopifnot(file.rename(hold,paste0(hold,".test-hold")))
must_fail(current_preflight(fixture,check_packages=FALSE))
stopifnot(file.rename(paste0(hold,".test-hold"),hold))
forbidden<-file.path(getwd(),paste0("runner_safety_",Sys.getpid()))
must_fail(prepare_current_workspace(forbidden,fixture,check_packages=FALSE));stopifnot(!dir.exists(forbidden))
destination<-tempfile("smoking_runner_workspace_")
ws<-prepare_current_workspace(destination,fixture,check_packages=FALSE)
stopifnot(normalizePath(file.path(ws,"age45_revision/derived"))==normalizePath(file.path(fixture,"age45_revision/derived")),
  !length(list.files(file.path(ws,"age45_revision/outputs"),recursive=TRUE)))
invisible(capture.output(run_current_analysis(ws)))
stopifnot(!length(list.files(file.path(ws,"age45_revision/outputs"),recursive=TRUE)))
must_fail(prepare_current_workspace(destination,fixture,check_packages=FALSE))
must_fail(run_current_analysis(fixture))
cat("PASS: source-only behavior, 53-step plan, missing-input/overwrite/repo-write guards, isolated code and dry run. No model was fitted.\n")
